env: foodbank

env_args:
  full_observable: False
  episode_limit: 50
  debug: True

  situation_name: "20a20f_c1"

  reward_mean_weight: 1
  reward_std_weight: 1
  reward_complete_bonus: 1
  reward_step_cost: -0.01
  
  disable_strategic_wait: True # Trueなら、取得可能な食品がある時は待機行動を選ばないようにする

  # n_agents: 2
  # n_foods: 2
  # initial_stock:
  #   - 5
  #   - 5
  # requests:
  #   - - 2
  #     - 3
  #   - - 3
  #     - 2

  # continuing_episode: False
  # difficulty: "7"
  # game_version: null
  # map_name: "3m"
  # move_amount: 2
  # obs_all_health: True
  # obs_instead_of_state: False
  # obs_last_action: False
  # obs_own_health: True
  # obs_pathing_grid: False
  # obs_terrain_height: False
  # obs_timestep_number: False
  # reward_death_value: 10
  # reward_defeat: 0
  # reward_negative_scale: 0.5
  # reward_only_positive: True
  # reward_scale: True
  # reward_scale_rate: 20
  # reward_sparse: False
  # reward_win: 200
  # replay_dir: ""
  # replay_prefix: ""
  # state_last_action: True
  # state_timestep_number: False
  # step_mul: 8
  # seed: null
  # heuristic_ai: False
  # heuristic_rest: False
  
